FROM node:12.20.0-alpine3.12 

WORKDIR /usr/app

COPY package*.json ./

RUN yarn

RUN mkdir src
RUN mkdir src/common
RUN mkdir src/services

COPY src/common src/common
COPY src/services/store.js src/services/store.js

EXPOSE 3000

CMD ["node", "src/services/store.js"]
