FROM node:12.20.0-alpine3.12 

WORKDIR /usr/app

COPY package*.json ./

RUN yarn

COPY src/common src/common
COPY src/services/acquirer.js src/services/acquirer.js

CMD ["node", "src/services/acquirer.js"]
